default_agent: agent_with_memory
agents:
  agentcore_lang_runtime:
    name: agentcore_lang_runtime
    language: python
    node_version: '20'
    entrypoint: C:/Users/acer/Downloads/agentWithAWS/01_agentcore_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\acer\Downloads\agentWithAWS
    aws:
      execution_role: arn:aws:iam::244489252552:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-c980c3716d
      execution_role_auto_create: false
      account: '244489252552'
      region: us-east-2
      ecr_repository: 244489252552.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-agentcore_lang_runtime
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_lang_runtime-JKKpZm7CDX
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:244489252552:runtime/agentcore_lang_runtime-JKKpZm7CDX
      agent_session_id: c3b266b7-062b-472c-9638-25751a44212b
    codebuild:
      project_name: bedrock-agentcore-agentcore_lang_runtime-builder
      execution_role: arn:aws:iam::244489252552:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-2-c980c3716d
      source_bucket: bedrock-agentcore-codebuild-sources-244489252552-us-east-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  agent_with_memory:
    name: agent_with_memory
    language: python
    node_version: '20'
    entrypoint: C:/Users/acer/Downloads/agentWithAWS/02_agentcore_memory.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\acer\Downloads\agentWithAWS
    aws:
      execution_role: arn:aws:iam::244489252552:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-f3cb8b6d58
      execution_role_auto_create: false
      account: '244489252552'
      region: us-east-2
      ecr_repository: 244489252552.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-agent_with_memory
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agent_with_memory-c3eaQN4Z6s
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:244489252552:runtime/agent_with_memory-c3eaQN4Z6s
      agent_session_id: dbd611af-f998-4873-9838-19f2d3a9caba
    codebuild:
      project_name: bedrock-agentcore-agent_with_memory-builder
      execution_role: arn:aws:iam::244489252552:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-2-f3cb8b6d58
      source_bucket: bedrock-agentcore-codebuild-sources-244489252552-us-east-2
    memory:
      mode: STM_AND_LTM
      memory_id: customer_care_agent_memory-MDsK377pfS
      memory_arn: null
      memory_name: agent_with_memory_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
